ignore:
    - .git
    - venv
    - .venv
    - env
    - .env
    - .tox
    - node_modules
    - vendor
    - use-text-content
    - dom-xss
    - javascript/xss
    - javascript.browser.security.insecure-innerhtml
    - javascript.browser.security.insecure-document-method
